language: php

php:
  - 7.0
  - 7.1

services:
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

dist: trusty

sudo: required

script:
  - npm install
  - npm test
