# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      rewards-service:
        container_name: rewards-api
        build: ./
        command: npm start
        working_dir: /Workspace/fec-capstone/rewards
        env_file:
          - ./server/src/config/.env
        ports:
          - "3005:3005"
        environment:
          DATABASE_HOST: mysql
          MYSQL_URI: mysql://root:password@mysql:3307/kstart
          REDIS_URI: redis://redis:6380

      # MySQL
      mysql:
        image: mysql
        container_name: rewards-mysql
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: kstart
          MYSQL_USER: k-user
          MYSQL_PASSWORD: k-pass
        ports:
          - "3307:3307"

      # Redis
      redis:
        image: redis
        container_name: rewards-redis
        ports:
          - "6380:6380"
workflows:
  version: 2
  build-deploy:
    jobs:
      - build


## PHP CircleCI 2.0 configuration file
##
## Check https://circleci.com/docs/2.0/language-php/ for more details
##
#version: 2
#jobs:
#  build:
#    docker:
#      # specify the version you desire here
#      - image: circleci/php:7.2-apache-stretch-node-browsers
#        environment:
#          MYSQL_ROOT_PASSWORD: password
#          MYSQL_HOST: 127.0.0.1
#          PORT: 3005
#          DATABASE_NAME: kstart
#          DATABASE_USER: myuser
#          DATABASE_PASSWORD: password
#          DEBUG: server:startup,database:startup
#
#      # Specify service dependencies here if necessary
#      # CircleCI maintains a library of pre-built images
#      # documented at https://circleci.com/docs/2.0/circleci-images/
#      # - image: circleci/mysql:9.4
#
#    steps:
#      - checkout
#      - run:
#          name: Install MySQL dependencies
#          command: |
#            sudo apt-get update
#            sudo apt-get install -y libzip-dev
#            sudo apt-get install -y zlib1g-dev libicu-dev g++
#            sudo apt-get install mysql-client
#            sudo apt-get -y install mysql-server
#      - run:
#          name: Install PHP exts
#          command: |
#            sudo docker-php-ext-install zip
#            sudo docker-php-ext-configure intl
#            sudo docker-php-ext-install intl
#            sudo docker-php-ext-install pdo_mysql
#      - run:
#          name: Fix MySQL socket config
#          command: |
#            sudo sh -c "echo 'pdo_mysql.default_socket=/var/run/mysqld/mysqld.sock' > /usr/local/etc/php/conf.d/pdo.ini"
#      - run:
#          name: Start database server
#          command: |
#            sudo service mysql start
#            sleep 2
#            ps aux | grep mysql
#      - run:
#          name: Create non-admin user
#          command: |
#            sudo mysql -u root -e "CREATE user myuser IDENTIFIED BY 'password';"
#      - run:
#          name: Install node packages
#          command: |
#            npm install
#      - run:
#          name: Run test suite
#          command: |
#            npm test
#
#workflows:
#  version: 2
#  build-deploy:
#    jobs:
#      - build
