version: 2.0
jobs:
  build:
    docker:
      - image: circleci/php:7.1-apache-node-browsers # The primary container where steps are run
      - image: circleci/mysql:latest
        environment:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: kstart
          MYSQL_USER: user
          MYSQL_PASSWORD: passw0rd
          DATABASE_NAME: kstart
          DATABASE_USER: user
          DATABASE_PASSWORD: passw0rd
    steps:
      - checkout
      - run:
          name: Install Dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for database connection
          command: dockerize -wait tcp://localhost:3306 -timeout 3m
      - run:
          name: Install MySQL CLI; Import dummy data; run an example query
          command: |
            sudo apt-get update
            sudo apt-get install mysql-client --fix-missing
            mysql -h 127.0.0.1 -u user -ppassw0rd
      - run:
          name: Install node packages
          command: |
            npm install
      - run:
          name: Run test suite
          command: |
            npm test
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
