#version: 2.0
#jobs:
#  build:
#    docker:
#      - image: circleci/php:7.1-apache-node-browsers # The primary container where steps are run
#      - image: circleci/mysql:latest
#    environment:
#      MYSQL_ROOT_PASSWORD: password
#      MYSQL_DATABASE: kstart
#      MYSQL_USER: user
#      MYSQL_PASSWORD: pass
#    steps:
#      - checkout
#      - run:
#          name: Install Dockerize
#          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
#          environment:
#            DOCKERIZE_VERSION: v0.3.0
#      - run:
#          name: Wait for database connection
#          command: dockerize -wait tcp://localhost:3306 -timeout 3m
#      - run:
#          name: Install node packages
#          command: npm install
#      - run:
#          name: Run test suite
#          command: npm test
#          environment:
#            PORT: 3005
#            DATABASE_NAME: kstart
#            DATABASE_USER: root
#            DATABASE_PASSWORD: password
#            DATABASE_HOST: localhost
#            DEBUG: server:startup,database:startup
#workflows:
#  version: 2
#  build-deploy:
#    jobs:
#      - build

version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:9.4
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_DATABASE=kstart
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_RANDOM_ROOT_PASSWORD=yes

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - setup_remote_docker

      - run:
          name: Build Docker Container
          command: sudo docker-compose up --build

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run Test Suite
          command: npm test
          environment:
            PORT: 3005
            DATABASE_NAME: kstart
            DATABASE_USER: root
            DATABASE_PASSWORD: password
            DATABASE_HOST: localhost
            DEBUG: server:startup,database:startup




